name: 'Install Gitea Tea CLI'
description: 'Installs and configures the Gitea CLI (tea) tool'
author: 'LiquidLogicLabs'
inputs:
  version:
    description: 'Version of tea to install (e.g., "latest", "v0.9.0", "0.9.0")'
    required: false
    default: 'latest'
  username:
    description: 'Gitea username for authentication'
    required: false
    default: ''
  token:
    description: 'Gitea personal access token. If not provided, will use GITEA_TOKEN or GITHUB_TOKEN environment variables'
    required: false
    default: ''
  repo:
    description: 'Gitea repository URL (e.g., https://gitea.com or https://gitea.example.com)'
    required: false
    default: ''
  skipCertificateCheck:
    description: 'Skip TLS certificate verification when downloading tea or calling APIs'
    required: false
    default: 'false'
  verbose:
    description: 'Enable verbose debug logging. Also enabled when ACTIONS_STEP_DEBUG=true.'
    required: false
    default: 'false'
outputs:
  success:
    description: 'Indicates if the installation was successful'
    value: ${{ steps.install-tea.outputs.success }}
  binaryPath:
    description: 'Path where the tea binary was installed'
    value: ${{ steps.install-tea.outputs.binaryPath }}
  version:
    description: 'Version of tea that was installed'
    value: ${{ steps.install-tea.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Install and configure tea
      id: install-tea
      shell: bash
      run: ${{ github.action_path }}/install-tea.sh
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_SKIP_CERTIFICATE_CHECK: ${{ inputs.skipCertificateCheck }}
        INPUT_VERBOSE: ${{ inputs.verbose == 'true' || env.ACTIONS_STEP_DEBUG == 'true' }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
branding:
  icon: 'terminal'
  color: 'blue'
